2025-02-27 08:54:55,022 Could not connect to Redis instance: Connection closed by server. Retrying in 2 seconds...
2025-02-27 09:18:28,071 Could not connect to Redis instance: Connection closed by server. Retrying in 2 seconds...
2025-02-27 09:23:03,877 Could not connect to Redis instance: Connection closed by server. Retrying in 2 seconds...
2025-02-27 09:26:16,589 [Job erp.localhost||e4a43de9-ce80-4fd1-91f2-4e75dc940a3f]: exception raised while executing (frappe.utils.background_jobs.execute_job)
Traceback (most recent call last):
  File "/home/nazmul/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 1633, in perform_job
    return_value = job.perform()
  File "/home/nazmul/frappe-bench/env/lib/python3.10/site-packages/rq/job.py", line 1331, in perform
    self._result = self._execute()
  File "/home/nazmul/frappe-bench/env/lib/python3.10/site-packages/rq/job.py", line 1365, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 221, in execute_job
    frappe.init(site, force=True)
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 309, in init
    setup_module_map(include_all_apps=not (frappe.request or frappe.job or frappe.flags.in_migrate))
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1632, in setup_module_map
    for module in get_module_list(app):
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1478, in get_module_list
    return get_file_items(get_app_path(app_name, "modules.txt"))
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1443, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1473, in get_pymodule_path
    return abspath(join(dirname(get_module(scrub(modulename)).__file__ or ""), *joins))
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1414, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'erpnext'

2025-02-27 09:26:16,597 [Job erp.localhost||166359a6-38d5-42ba-9847-1748be77da64]: exception raised while executing (frappe.utils.background_jobs.execute_job)
Traceback (most recent call last):
  File "/home/nazmul/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 1633, in perform_job
    return_value = job.perform()
  File "/home/nazmul/frappe-bench/env/lib/python3.10/site-packages/rq/job.py", line 1331, in perform
    self._result = self._execute()
  File "/home/nazmul/frappe-bench/env/lib/python3.10/site-packages/rq/job.py", line 1365, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 221, in execute_job
    frappe.init(site, force=True)
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 309, in init
    setup_module_map(include_all_apps=not (frappe.request or frappe.job or frappe.flags.in_migrate))
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1632, in setup_module_map
    for module in get_module_list(app):
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1478, in get_module_list
    return get_file_items(get_app_path(app_name, "modules.txt"))
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1443, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1473, in get_pymodule_path
    return abspath(join(dirname(get_module(scrub(modulename)).__file__ or ""), *joins))
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1414, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'erpnext'

2025-02-27 09:26:16,605 [Job erp.localhost||997fb11a-968c-47d9-8fd4-9dca6a343e1b]: exception raised while executing (frappe.utils.background_jobs.execute_job)
Traceback (most recent call last):
  File "/home/nazmul/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 1633, in perform_job
    return_value = job.perform()
  File "/home/nazmul/frappe-bench/env/lib/python3.10/site-packages/rq/job.py", line 1331, in perform
    self._result = self._execute()
  File "/home/nazmul/frappe-bench/env/lib/python3.10/site-packages/rq/job.py", line 1365, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 221, in execute_job
    frappe.init(site, force=True)
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 309, in init
    setup_module_map(include_all_apps=not (frappe.request or frappe.job or frappe.flags.in_migrate))
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1632, in setup_module_map
    for module in get_module_list(app):
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1478, in get_module_list
    return get_file_items(get_app_path(app_name, "modules.txt"))
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1443, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1473, in get_pymodule_path
    return abspath(join(dirname(get_module(scrub(modulename)).__file__ or ""), *joins))
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1414, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'erpnext'

2025-02-27 09:26:16,613 [Job erp.localhost||8fa2cbc5-5ee9-48f6-8a39-01c6ddc8bd37]: exception raised while executing (frappe.utils.background_jobs.execute_job)
Traceback (most recent call last):
  File "/home/nazmul/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 1633, in perform_job
    return_value = job.perform()
  File "/home/nazmul/frappe-bench/env/lib/python3.10/site-packages/rq/job.py", line 1331, in perform
    self._result = self._execute()
  File "/home/nazmul/frappe-bench/env/lib/python3.10/site-packages/rq/job.py", line 1365, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 221, in execute_job
    frappe.init(site, force=True)
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 309, in init
    setup_module_map(include_all_apps=not (frappe.request or frappe.job or frappe.flags.in_migrate))
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1632, in setup_module_map
    for module in get_module_list(app):
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1478, in get_module_list
    return get_file_items(get_app_path(app_name, "modules.txt"))
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1443, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1473, in get_pymodule_path
    return abspath(join(dirname(get_module(scrub(modulename)).__file__ or ""), *joins))
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1414, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'erpnext'

2025-02-27 09:26:16,620 [Job erp.localhost||380c443e-59b8-498c-88f3-8d72e0b18397]: exception raised while executing (frappe.utils.background_jobs.execute_job)
Traceback (most recent call last):
  File "/home/nazmul/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 1633, in perform_job
    return_value = job.perform()
  File "/home/nazmul/frappe-bench/env/lib/python3.10/site-packages/rq/job.py", line 1331, in perform
    self._result = self._execute()
  File "/home/nazmul/frappe-bench/env/lib/python3.10/site-packages/rq/job.py", line 1365, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 221, in execute_job
    frappe.init(site, force=True)
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 309, in init
    setup_module_map(include_all_apps=not (frappe.request or frappe.job or frappe.flags.in_migrate))
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1632, in setup_module_map
    for module in get_module_list(app):
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1478, in get_module_list
    return get_file_items(get_app_path(app_name, "modules.txt"))
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1443, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1473, in get_pymodule_path
    return abspath(join(dirname(get_module(scrub(modulename)).__file__ or ""), *joins))
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1414, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'erpnext'

2025-02-27 09:26:16,628 [Job erp.localhost||ac0159ea-44d0-45e1-b824-0404864cfaff]: exception raised while executing (frappe.utils.background_jobs.execute_job)
Traceback (most recent call last):
  File "/home/nazmul/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 1633, in perform_job
    return_value = job.perform()
  File "/home/nazmul/frappe-bench/env/lib/python3.10/site-packages/rq/job.py", line 1331, in perform
    self._result = self._execute()
  File "/home/nazmul/frappe-bench/env/lib/python3.10/site-packages/rq/job.py", line 1365, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 221, in execute_job
    frappe.init(site, force=True)
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 309, in init
    setup_module_map(include_all_apps=not (frappe.request or frappe.job or frappe.flags.in_migrate))
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1632, in setup_module_map
    for module in get_module_list(app):
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1478, in get_module_list
    return get_file_items(get_app_path(app_name, "modules.txt"))
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1443, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1473, in get_pymodule_path
    return abspath(join(dirname(get_module(scrub(modulename)).__file__ or ""), *joins))
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1414, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'erpnext'

2025-02-27 09:26:16,637 [Job erp.localhost||d488dc6e-c34f-43a0-a7c2-1a316022b328]: exception raised while executing (frappe.utils.background_jobs.execute_job)
Traceback (most recent call last):
  File "/home/nazmul/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 1633, in perform_job
    return_value = job.perform()
  File "/home/nazmul/frappe-bench/env/lib/python3.10/site-packages/rq/job.py", line 1331, in perform
    self._result = self._execute()
  File "/home/nazmul/frappe-bench/env/lib/python3.10/site-packages/rq/job.py", line 1365, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 221, in execute_job
    frappe.init(site, force=True)
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 309, in init
    setup_module_map(include_all_apps=not (frappe.request or frappe.job or frappe.flags.in_migrate))
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1632, in setup_module_map
    for module in get_module_list(app):
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1478, in get_module_list
    return get_file_items(get_app_path(app_name, "modules.txt"))
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1443, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1473, in get_pymodule_path
    return abspath(join(dirname(get_module(scrub(modulename)).__file__ or ""), *joins))
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1414, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'erpnext'

2025-02-27 09:26:16,645 [Job erp.localhost||e9703244-7095-4abc-9b3e-629d85b032bf]: exception raised while executing (frappe.utils.background_jobs.execute_job)
Traceback (most recent call last):
  File "/home/nazmul/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 1633, in perform_job
    return_value = job.perform()
  File "/home/nazmul/frappe-bench/env/lib/python3.10/site-packages/rq/job.py", line 1331, in perform
    self._result = self._execute()
  File "/home/nazmul/frappe-bench/env/lib/python3.10/site-packages/rq/job.py", line 1365, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 221, in execute_job
    frappe.init(site, force=True)
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 309, in init
    setup_module_map(include_all_apps=not (frappe.request or frappe.job or frappe.flags.in_migrate))
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1632, in setup_module_map
    for module in get_module_list(app):
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1478, in get_module_list
    return get_file_items(get_app_path(app_name, "modules.txt"))
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1443, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1473, in get_pymodule_path
    return abspath(join(dirname(get_module(scrub(modulename)).__file__ or ""), *joins))
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1414, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'erpnext'

2025-02-27 09:26:16,654 [Job erp.localhost||4dede822-9da6-4980-9a08-4e7d94e185f2]: exception raised while executing (frappe.utils.background_jobs.execute_job)
Traceback (most recent call last):
  File "/home/nazmul/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 1633, in perform_job
    return_value = job.perform()
  File "/home/nazmul/frappe-bench/env/lib/python3.10/site-packages/rq/job.py", line 1331, in perform
    self._result = self._execute()
  File "/home/nazmul/frappe-bench/env/lib/python3.10/site-packages/rq/job.py", line 1365, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 221, in execute_job
    frappe.init(site, force=True)
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 309, in init
    setup_module_map(include_all_apps=not (frappe.request or frappe.job or frappe.flags.in_migrate))
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1632, in setup_module_map
    for module in get_module_list(app):
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1478, in get_module_list
    return get_file_items(get_app_path(app_name, "modules.txt"))
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1443, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1473, in get_pymodule_path
    return abspath(join(dirname(get_module(scrub(modulename)).__file__ or ""), *joins))
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1414, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'erpnext'

2025-02-27 09:26:16,661 [Job erp.localhost||33052421-77ff-44bd-9e62-64705e50a11b]: exception raised while executing (frappe.utils.background_jobs.execute_job)
Traceback (most recent call last):
  File "/home/nazmul/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 1633, in perform_job
    return_value = job.perform()
  File "/home/nazmul/frappe-bench/env/lib/python3.10/site-packages/rq/job.py", line 1331, in perform
    self._result = self._execute()
  File "/home/nazmul/frappe-bench/env/lib/python3.10/site-packages/rq/job.py", line 1365, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 221, in execute_job
    frappe.init(site, force=True)
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 309, in init
    setup_module_map(include_all_apps=not (frappe.request or frappe.job or frappe.flags.in_migrate))
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1632, in setup_module_map
    for module in get_module_list(app):
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1478, in get_module_list
    return get_file_items(get_app_path(app_name, "modules.txt"))
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1443, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1473, in get_pymodule_path
    return abspath(join(dirname(get_module(scrub(modulename)).__file__ or ""), *joins))
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1414, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'erpnext'

2025-02-27 09:26:16,669 [Job erp.localhost||9a71ac94-b14d-4f56-b270-8fd5f2509f56]: exception raised while executing (frappe.utils.background_jobs.execute_job)
Traceback (most recent call last):
  File "/home/nazmul/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 1633, in perform_job
    return_value = job.perform()
  File "/home/nazmul/frappe-bench/env/lib/python3.10/site-packages/rq/job.py", line 1331, in perform
    self._result = self._execute()
  File "/home/nazmul/frappe-bench/env/lib/python3.10/site-packages/rq/job.py", line 1365, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 221, in execute_job
    frappe.init(site, force=True)
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 309, in init
    setup_module_map(include_all_apps=not (frappe.request or frappe.job or frappe.flags.in_migrate))
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1632, in setup_module_map
    for module in get_module_list(app):
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1478, in get_module_list
    return get_file_items(get_app_path(app_name, "modules.txt"))
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1443, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1473, in get_pymodule_path
    return abspath(join(dirname(get_module(scrub(modulename)).__file__ or ""), *joins))
  File "/home/nazmul/frappe-bench/apps/frappe/frappe/__init__.py", line 1414, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'erpnext'

2025-02-27 09:28:00,907 Could not connect to Redis instance: Connection closed by server. Retrying in 2 seconds...
/home/nazmul/frappe-bench/apps/erpnext/erpnext/accounts/utils.py:1114: V16FrappeDeprecationWarning: frappe.utils.data.get_number_format_info is deprecated.
It was marked on unknown for removal from v16 with note: Use `NumberFormat.from_string()` from `frappe.utils.number_format` instead
  precision = get_number_format_info(number_format)[2]
/home/nazmul/frappe-bench/env/lib/python3.10/site-packages/pypdf/_crypt_providers/_cryptography.py:32: CryptographyDeprecationWarning: ARC4 has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.ARC4 and will be removed from cryptography.hazmat.primitives.ciphers.algorithms in 48.0.0.
  from cryptography.hazmat.primitives.ciphers.algorithms import AES, ARC4
/home/nazmul/frappe-bench/env/lib/python3.10/site-packages/pypdf/_crypt_providers/_cryptography.py:32: CryptographyDeprecationWarning: ARC4 has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.ARC4 and will be removed from cryptography.hazmat.primitives.ciphers.algorithms in 48.0.0.
  from cryptography.hazmat.primitives.ciphers.algorithms import AES, ARC4
2025-02-27 09:38:22,894 Could not connect to Redis instance: Connection closed by server. Retrying in 2 seconds...
/home/nazmul/frappe-bench/env/lib/python3.10/site-packages/pypdf/_crypt_providers/_cryptography.py:32: CryptographyDeprecationWarning: ARC4 has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.ARC4 and will be removed from cryptography.hazmat.primitives.ciphers.algorithms in 48.0.0.
  from cryptography.hazmat.primitives.ciphers.algorithms import AES, ARC4
/home/nazmul/frappe-bench/env/lib/python3.10/site-packages/pypdf/_crypt_providers/_cryptography.py:32: CryptographyDeprecationWarning: ARC4 has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.ARC4 and will be removed from cryptography.hazmat.primitives.ciphers.algorithms in 48.0.0.
  from cryptography.hazmat.primitives.ciphers.algorithms import AES, ARC4
/home/nazmul/frappe-bench/env/lib/python3.10/site-packages/pypdf/_crypt_providers/_cryptography.py:32: CryptographyDeprecationWarning: ARC4 has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.ARC4 and will be removed from cryptography.hazmat.primitives.ciphers.algorithms in 48.0.0.
  from cryptography.hazmat.primitives.ciphers.algorithms import AES, ARC4
/home/nazmul/frappe-bench/env/lib/python3.10/site-packages/pypdf/_crypt_providers/_cryptography.py:32: CryptographyDeprecationWarning: ARC4 has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.ARC4 and will be removed from cryptography.hazmat.primitives.ciphers.algorithms in 48.0.0.
  from cryptography.hazmat.primitives.ciphers.algorithms import AES, ARC4
/home/nazmul/frappe-bench/env/lib/python3.10/site-packages/pypdf/_crypt_providers/_cryptography.py:32: CryptographyDeprecationWarning: ARC4 has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.ARC4 and will be removed from cryptography.hazmat.primitives.ciphers.algorithms in 48.0.0.
  from cryptography.hazmat.primitives.ciphers.algorithms import AES, ARC4
/home/nazmul/frappe-bench/env/lib/python3.10/site-packages/pypdf/_crypt_providers/_cryptography.py:32: CryptographyDeprecationWarning: ARC4 has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.ARC4 and will be removed from cryptography.hazmat.primitives.ciphers.algorithms in 48.0.0.
  from cryptography.hazmat.primitives.ciphers.algorithms import AES, ARC4
/home/nazmul/frappe-bench/apps/erpnext/erpnext/accounts/utils.py:1114: V16FrappeDeprecationWarning: frappe.utils.data.get_number_format_info is deprecated.
It was marked on unknown for removal from v16 with note: Use `NumberFormat.from_string()` from `frappe.utils.number_format` instead
  precision = get_number_format_info(number_format)[2]
/home/nazmul/frappe-bench/env/lib/python3.10/site-packages/pypdf/_crypt_providers/_cryptography.py:32: CryptographyDeprecationWarning: ARC4 has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.ARC4 and will be removed from cryptography.hazmat.primitives.ciphers.algorithms in 48.0.0.
  from cryptography.hazmat.primitives.ciphers.algorithms import AES, ARC4
/home/nazmul/frappe-bench/env/lib/python3.10/site-packages/pypdf/_crypt_providers/_cryptography.py:32: CryptographyDeprecationWarning: ARC4 has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.ARC4 and will be removed from cryptography.hazmat.primitives.ciphers.algorithms in 48.0.0.
  from cryptography.hazmat.primitives.ciphers.algorithms import AES, ARC4
2025-02-27 10:27:09,994 Could not connect to Redis instance: Connection closed by server. Retrying in 2 seconds...
